### ISSUE TITLE
eecs126找不到public video资源

### ISSUE THREAD

**Issue by maiixu** [PKUFlyingPig/EECS126#1]
Hi，请问在哪里可以找到eecs126的视频资源呢？在b站，youtube和google都搜了没有找到，如果可以的话请share一下链接，十分感谢！

**Comment by PKUFlyingPig** [comment]
eecs126我也没找到视频资源，但是notes和配套的教材写得很好很全面，感觉不太需要视频。

**Comment by maiixu** [comment]
> 

收到！多谢建议！
